### ISSUE TITLE
Reproducing Schreiber's article using IDTxl

### ISSUE THREAD

**Issue by mghadam** [pwollstadt/IDTxl#59] opened 2020-11-22 10:32 UTC
I'm trying to reproduce Example 3 in Schreiber 2000's seminal article using IDTxl [here](https://colab.research.google.com/drive/1UE6nb2dL00942fkf_sQeq7tzMCaUYJup?usp=sharing). 

![image](https://user-images.githubusercontent.com/10244293/99901337-591d2e80-2ccb-11eb-9852-a25908dcae7f.png)

I wonder if it is possible at all to reproduce such results with IDTxl and get the same TE numbers to reproduce the figure in question?

**Comment by jlizier** [comment] 2020-11-23 06:04
The answer is yes and no.

In principle yes, because the reproduction of these results is achievable via [JIDT](https://github.com/jlizier/jidt) -- one of the information theory engines under the hood in IDTxl -- as described one one of its [wiki pages](https://github.com/jlizier/jidt/wiki/SchreiberTeDemos).

With that said, this example requires a kernel density estimator for TE, which is available in JIDT under the hood but we have opted not to make available at the user level in IDTxl. This is because our preferred KSG estimator is much more stable w.r.t. underlying parameters, as shown on the aforementioned [JIDT demonstration](https://github.com/jlizier/jidt/wiki/SchreiberTeDemos). (It's also worth noting that a number of crucial details about that example were omitted from the Schreiber paper, as detailed on that wiki page).

If you simply want to recreate that example, I would suggest you do this via JIDT following the instructions on that wiki page. If you specifically want to use IDTxl, then the closest you would come is to make the estimates via the KSG estimator, following the last section of the JIDT wiki page there. (Note: we will not be recreating this here).

Closing: this is not a bug, and the demo is not going to be added since it's redundant with JIDT.

**Closed by jlizier** 2020-11-23 06:04 UTC
