### ISSUE TITLE
No module named 'idtxl' error while running exe

### ISSUE THREAD

**Issue by n2ghtwish** [pwollstadt/IDTxl#42] opened 2019-12-12 07:20 UTC
Hi!
I wrote a GUI to run the analysis. From the IDE (Pycharm) everything works fine. But there is a problem with exe file, which is compiled using 'pyinstaller'.
Error is "No module named 'idtxl'".
There was no errors during compile process.
Can you help me to solve this error?
p.s. IDTxl installed as described in https://github.com/pwollstadt/IDTxl/issues/26#issuecomment-454148394

**Comment by pwollstadt** [comment] 2020-04-14 12:15
Hi @n2ghtwish, I am afraid this is beyond the support we can offer here. To me, this sounds like an issue with your python setup. Also, we don't provide Windows support for IDTxl. Hence, I will close this issue. If you find out, the problem is related to a bug in IDTxl, feel free to reopen. Thank you!

**Closed by pwollstadt** 2020-04-14 12:15 UTC
